services:
  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ecom-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8000:8000"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Product Service
  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    container_name: ecom-product-service
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - PRODUCTS_TABLE_NAME=ecom-products
      - PORT=8001
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
    ports:
      - "8001:8001"
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - ecom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Cart Service  
  cart-service:
    build:
      context: ./backend
      dockerfile: cart-service/Dockerfile
    container_name: ecom-cart-service
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - CARTS_TABLE_NAME=ecom-carts
      - PORT=8002
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - PRODUCT_SERVICE_URL=http://product-service:8001/api
    ports:
      - "8002:8002"
    depends_on:
      dynamodb-local:
        condition: service_healthy
      product-service:
        condition: service_healthy
    networks:
      - ecom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecom-frontend
    environment:
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:8001/api
      - REACT_APP_CART_SERVICE_URL=http://localhost:8002/api
    ports:
      - "3000:80"
    depends_on:
      - product-service
      - cart-service
    networks:
      - ecom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dynamodb_data:
    driver: local

networks:
  ecom-network:
    driver: bridge