version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # DynamoDB Local (same as production)
  dynamodb-local:
    ports:
      - "8000:8000"

  # Product Service (Development mode)
  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    container_name: ecom-product-service-dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend/product-service/app:/app/app:ro
      - ./backend/shared:/app/shared:ro
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - PRODUCTS_TABLE_NAME=ecom-products
      - PORT=8001
      - JWT_SECRET_KEY=dev-secret-key-that-is-at-least-32-characters-long-for-development
      - USE_COGNITO_AUTH=false
      - PYTHONPATH=/app
    depends_on:
      - dynamodb-local
    networks:
      - ecom-network
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Cart Service (Development mode)
  cart-service:
    build:
      context: ./backend
      dockerfile: cart-service/Dockerfile
    container_name: ecom-cart-service-dev
    ports:
      - "8002:8002"
    volumes:
      - ./backend/cart-service/app:/app/app:ro
      - ./backend/shared:/app/shared:ro
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - CARTS_TABLE_NAME=ecom-carts
      - PORT=8002
      - JWT_SECRET_KEY=dev-secret-key-that-is-at-least-32-characters-long-for-development
      - USE_COGNITO_AUTH=false
      - PRODUCT_SERVICE_URL=http://product-service:8001/api
      - PYTHONPATH=/app
    depends_on:
      - dynamodb-local
      - product-service
    networks:
      - ecom-network
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  # Frontend Development Server (overrides production frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ecom-frontend-dev
    environment:
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:8001/api
      - REACT_APP_CART_SERVICE_URL=http://localhost:8002/api
      - REACT_APP_USE_COGNITO_AUTH=false
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    depends_on:
      - product-service
      - cart-service
    networks:
      - ecom-network