# Local Development Docker Compose Configuration
# Usage: docker-compose up --build

services:
  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ecom-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8000:8000"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Product Service (Development mode)
  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    container_name: ecom-product-service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/product-service/app:/var/task/app:ro
      - ./backend/shared:/var/task/shared:ro
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - PRODUCTS_TABLE_NAME=ecom-products
      - PORT=8001
      - JWT_SECRET_KEY=dev-secret-key-that-is-at-least-32-characters-long-for-development
      - USE_COGNITO_AUTH=false
      - PYTHONPATH=/var/task
    depends_on:
      - dynamodb-local
    networks:
      - ecom-network
    entrypoint: []
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Cart Service (Development mode)
  cart-service:
    build:
      context: ./backend
      dockerfile: cart-service/Dockerfile
    container_name: ecom-cart-service
    ports:
      - "8002:8002"
    volumes:
      - ./backend/cart-service/app:/var/task/app:ro
      - ./backend/shared:/var/task/shared:ro
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - CARTS_TABLE_NAME=ecom-carts
      - PORT=8002
      - JWT_SECRET_KEY=dev-secret-key-that-is-at-least-32-characters-long-for-development
      - USE_COGNITO_AUTH=false
      - PRODUCT_SERVICE_URL=http://product-service:8001/api
      - PYTHONPATH=/var/task
    depends_on:
      - dynamodb-local
      - product-service
    networks:
      - ecom-network
    entrypoint: []
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  
    container_name: ecom-frontend
    environment:
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:8001/api
      - REACT_APP_CART_SERVICE_URL=http://localhost:8002/api
      - REACT_APP_USE_COGNITO_AUTH=false
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    depends_on:
      - product-service
      - cart-service
    networks:
      - ecom-network

volumes:
  dynamodb_data:
    driver: local

networks:
  ecom-network:
    driver: bridge